# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Round 2 against bots

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Build release
        run: cargo build --release

      - name: Rrun game
        run: |
          cd runner
          python3 game_runner.py round_2_bots 10 80